service: crud
useDotenv: true

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    restApiId: ${cf:restApi-${self:provider.stage}.ApiGatewayRestApiId}
    restApiRootResourceId: ${cf:restApi-${self:provider.stage}.ApiGatewayRestApiResourceId}

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!node_modules/**/src/**'
    - '!src/**'
    - '!scripts/**'
    - '!dist/**'
    - '!layers/**'
    - '!database/**'
    - '!schema.prisma'
    - '!tsconfig.json'
    - '!tslint.json'
    - 'prisma/**'
    - 'node_modules/.prisma/**'

functions:
  crud:
    handler: dist/endpoints/crud/api.handler
    package:
      patterns:
        - 'dist/endpoints/crud/api/handler.js'
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
    events:
      - http:
          path: /{proxy+}
          method: any
